package io.zhijun.spring.boot.webmvc.constants;

import static io.zhijun.spring.boot.constants.PropertyConstants.ROSE_SPRING_BOOT_PROPERTY_NAME_PREFIX;

/**
 * WebMVC 配置属性常量
 */
public interface PropertyConstants {

    String ROSE_SPRING_BOOT_WEBMVC_PROPERTY_NAME_PREFIX = ROSE_SPRING_BOOT_PROPERTY_NAME_PREFIX + "webmvc.";

    String ROSE_SPRING_BOOT_WEBMVC_ENABLED_PROPERTY_NAME = ROSE_SPRING_BOOT_WEBMVC_PROPERTY_NAME_PREFIX + "enabled";

    String ROSE_SPRING_BOOT_WEBMVC_FILTER_ENABLED_PROPERTY_NAME = ROSE_SPRING_BOOT_WEBMVC_PROPERTY_NAME_PREFIX + "filter.enabled";

    String ROSE_SPRING_BOOT_WEBMVC_LOGGING_ENABLED_PROPERTY_NAME = ROSE_SPRING_BOOT_WEBMVC_PROPERTY_NAME_PREFIX + "logging.enabled";

    String ROSE_SPRING_BOOT_WEBMVC_CONTENT_NEGOTIATION_ENABLED_PROPERTY_NAME = ROSE_SPRING_BOOT_WEBMVC_PROPERTY_NAME_PREFIX + "content-negotiation.enabled";

    String ROSE_SPRING_BOOT_WEBMVC_VIEW_RESOLVER_ENABLED_PROPERTY_NAME = ROSE_SPRING_BOOT_WEBMVC_PROPERTY_NAME_PREFIX + "view-resolver.enabled";
}
